// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3Yi0EYLWyun_Mgoz0JL8RpPHTDchDiiU',
    appId: '1:319038610751:web:bf9f48414ee897508cc78a',
    messagingSenderId: '319038610751',
    projectId: 'messenger-b5584',
    authDomain: 'messenger-b5584.firebaseapp.com',
    storageBucket: 'messenger-b5584.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQOSkBFXIJoRQyS5O9FUVyqvpa6pnFFd8',
    appId: '1:319038610751:android:561a632f440a73ff8cc78a',
    messagingSenderId: '319038610751',
    projectId: 'messenger-b5584',
    storageBucket: 'messenger-b5584.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhUGflUjHgRLnarIOH5ZO1N9GiPhYYZZw',
    appId: '1:319038610751:ios:b47ea79a79fdecd48cc78a',
    messagingSenderId: '319038610751',
    projectId: 'messenger-b5584',
    storageBucket: 'messenger-b5584.appspot.com',
    iosClientId: '319038610751-1ptifmgos277s4qbocd2v0uno2vc5gim.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
